title: ""
labels: ["idea"Z"]

body:
  - type: markdown
    attributes:
      value: |
        ## Propose a New Idea
        
        Please fill out the form below to help us understand your proposal.
        
        **Note:** This discussion uses voting. After submitting, others can vote on your idea using the ⬆️ upvote arrow (located on the left side of the discussion). Use the "Top" filter to view the most popular ideas!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What issue or limitation are you trying to solve?
      placeholder: Describe the problem in a few sentences.
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: How is this currently handled or worked around?
      placeholder: Describe the current situation or workaround.

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: What would be the ideal solution or improvement?
      placeholder: Explain the change you suggest and why it would help.
    validations:
      required: true

  - type: textarea
    id: attachments
    attributes:
      label: Supporting Documents or Screenshots
      description: Add links or markdown image embeds.  
      placeholder: Paste screenshots, mockups, or links to relevant files.
