title: "[Idea]: "
labels: ["idea"]
body:
  - type: markdown
    attributes:
      value: |
        ## Propose a New Idea
        
        Thank you for suggesting a new idea for gyp_future! Please fill out the form below to help us understand your proposal.
        
        **Note:** This discussion uses voting. Please vote on ideas you support using the 👍 reaction!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of your idea
      placeholder: Describe your idea here...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this idea solve? What need does it address?
      placeholder: Explain the problem or need...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you implement this idea? What would it look like?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered? Why is your proposal better?
      placeholder: Describe alternative solutions...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, examples, or references
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this idea, you agree to follow our community guidelines
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
